name: Build JSON Format Converter

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Ensure zip utility is available (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Validate project
      run: |
        # Check if build artifacts exist (do not fail if absent)
        if compgen -G "*.zip" > /dev/null; then
          echo "Listing zip artifacts:" && ls -la *.zip
        else
          echo "No zip artifacts found"
        fi
        if [ -d dist ]; then
          echo "Listing dist directory:" && ls -la dist/
        else
          echo "dist/ directory not found"
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: json-format-converter-${{ github.sha }}
        path: |
          *.zip
          dist/
        retention-days: 30

    - name: Get version for release
      if: github.event_name == 'release'
      id: get_version
      run: echo "version=$(grep '"version"' package.json | head -1 | cut -d'"' -f4)" >> $GITHUB_OUTPUT

    - name: Upload Chrome Extension ZIP to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./json-format-converter-chrome.zip
        asset_name: json-format-converter-chrome-v${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip

    - name: Upload Firefox Extension ZIP to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./json-format-converter-firefox.zip
        asset_name: json-format-converter-firefox-v${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip

    - name: Upload Standalone ZIP to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./json-format-converter-standalone.zip
        asset_name: json-format-converter-standalone-v${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip
